### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#109]
I was checking the gene descriptions that I generated this morning and I
found that some FTP files (Gene IDs and Orthology for non-elegans
species) that had data in previous releases are now completely empty.
For example:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS279/species/c_japonica/PRJNA12591/annotation/c_japonica.PRJNA12591.WS279.geneIDs.txt.gz
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS279/species/c_japonica/PRJNA12591/annotation/c_japonica.PRJNA12591.WS279.orthologs.txt.gz

**Comment by MagdalenaZZ** [comment]
Valerio found this issue.

**Comment by epaule** [comment]
we rebuilt C.japonica in WS278, would be worth checking if it is like that since then.

**Comment by epaule** [comment]
Hi @valearna , good catch. I fixed the C.japonica ones for WS279 on the EBI FTP site. It should be fine for subsequent releases.

**Comment by valearna** [comment]
Thanks @epaule for fixing the C. japonica files. There are other species affected by the same issues and I still see empty files for: brenneri, briggsae, remanei, volvulus, pacificaus, ratti, and muris. WS278 files are ok.

**Comment by epaule** [comment]
Ok, I will do a "-all-species" version of that one

**Comment by valearna** [comment]
Thanks @epaule!

**Comment by MagdalenaZZ** [comment]
All of the files have now been generated, and @epaule is working out a way to transfer them over to the FTP.

**Comment by MagdalenaZZ** [comment]
We have now created the files, and transferred them to the FTP, and updated the CHECKSUMs, eg ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS279/species/c_briggsae/PRJNA10731/annotation/

**Comment by epaule** [comment]
hi @tharris , we just added/updated the missing files, could you resync it from the EBI for @valearna
